#!/bin/bash

export ANSIBLE_CONTAINER_VERSION="1.0"
export ANSIBLE_CONTAINER_IMAGE="ansible-celp:${ANSIBLE_CONTAINER_VERSION}"
export ANSIBLE_GALAXY_CONTAINER_IMAGE="ansible-galaxy-celp:${ANSIBLE_CONTAINER_VERSION}"
export ANSIBLE_PLAYBOOK_CONTAINER_IMAGE="ansible-playbook-celp:${ANSIBLE_CONTAINER_VERSION}"

